cricstarz/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('tournaments/', include('tournament.urls')),
    path('team/', include('teams.urls')),
    path('match/', include('matchs.urls')),
    path('player/', include('players.urls')),
]

home/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    path('', TemplateView.as_view(template_name='home/index.html'), name = 'home'),
    path('register/', views.register, name = 'register'),
]

tournament/urls.py
from django.urls import path, include
from . import views

app_name='tournaments'
urlpatterns = [
    path('all/', views.TournamentListView.as_view(), name='all'),
    path('create/', views.TournamentCreateView.as_view(), name='create'),
    path('view/<int:pk>/', views.TournamentDetailView.as_view(), name='detail'),
]

home/models.py
from django.db import models

# Create your models here.

home/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class CreateForm(UserCreationForm):
    email = forms.EmailField(required=True)
    
    class Meta:
        model = User
        fields = ('username',
                  'first_name',
                  'last_name',
                  'email',
                  'password1',
                  'password2',
                )
        
    def save(self, commit=True):
        user = super(CreateForm, self).save(commit=False)
        user.first_name = self.cleaned_data.get('first_name')
        user.last_name = self.cleaned_data.get('last_name')
        user.email = self.cleaned_data.get('email')
        
        if commit:
            user.save()
            
        return user

home/views.py
from django.shortcuts import redirect, render
from .forms import CreateForm
from django.contrib import messages

# Create your views here.

def register(request):
    if request.method == 'POST':
        form = CreateForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, f'Account created!')
            return redirect('login')
        else:
            messages.error(request, f'Ther was an error in your form!')
            return render(request, 'registration/register.html', {'form':form})
    else:
        form = CreateForm()
        
        args = {'form': form}
        return render(request, 'registration/register.html', args)

home/templates/base.html
{% load static %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang=en>
	<head>
		<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<!-- CSS only -->
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
		<title>Cricstarz</title>
	</head>

	<body>

		{% block navbar %}{% endblock navbar %}
		{% if messages %}
			{% for message in messages %}
				<div class="alert alert-{{ message.tags }}">
					{{ message }}
				</div>
			{% endfor %}
		{% endif %}


		<div class="container">

			{% block up %}{% endblock up %}

			{% block content %}{% endblock content %}
			<!-- JS, Popper.js, and jQuery -->
		</div>

		<footer class="footer" style="height: 20px;"></footer>
		
		<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

	</body>
</head>

home/templates/menu.html
{% extends 'base.html' %} {% block navbar %}
<header class="site-header">
  <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="{% url 'home' %}">Cricstarz</a>
    <button
      class="navbar-toggler"
      type="button"
      data-toggle="collapse"
      data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto justify-content-end">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home' %}">Home</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'tournaments:all' %}">Tournaments</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'tournaments:create' %}">Create Tournament</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'register' %}">Register</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>
  <br /><br />
</header>
{% endblock navbar %}