cricstarz/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('tournaments/', include('tournament.urls')),
    path('team/', include('teams.urls')),
    path('match/', include('matchs.urls')),
    path('player/', include('players.urls')),
]

home/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    path('', TemplateView.as_view(template_name='home/index.html'), name = 'home'),
    path('register/', views.register, name = 'register'),
]

matchs/urls.py
from django.urls import path
from . import views

app_name = 'match'
urlpatterns = [
    path('<int:tournamentid>/new/', views.MatchCreateView.as_view(), name="addmatch"),
]

players/urls.py
from django.urls import path
from . import views

app_name = 'players'
urlpatterns = [
    path('<int:tournamentid>/new/', views.PlayerCreateView.as_view(), name = "addplayer"),
]

teams/urls.py
from django.urls import path
from . import views

app_name="teams"
urlpatterns = [
    path('<int:tournamentid>/new/', views.TeamCreateView.as_view(), name="addteam"),
]

tournament/urls.py
from django.urls import path, include
from . import views

app_name='tournaments'
urlpatterns = [
    path('all/', views.TournamentListView.as_view(), name='all'),
    path('create/', views.TournamentCreateView.as_view(), name='create'),
    path('view/<int:pk>/', views.TournamentDetailView.as_view(), name='detail'),
]

matchs/models.py
from django.db import models
from tournament.models import Tournament
from teams.models import Team

class Match(models.Model):
    team1 = models.ForeignKey(Team, on_delete=models.PROTECT, related_name="team1")
    team2 = models.ForeignKey(Team, on_delete=models.PROTECT, related_name="team2")
    tournament = models.ForeignKey(Tournament, on_delete=models.PROTECT)
    winner = models.ForeignKey(Team, on_delete=models.PROTECT, related_name="winner", null=True)
    
    def __str__(self):
        return self.team1.name + " vs " + self.team2.name

tournament/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator

class Tournament(models.Model):
    name = models.CharField(max_length=128, unique=True, validators=[MinLengthValidator(2,'Minimum 2 Characters required')])
    no_of_overs = models.IntegerField()
    no_of_teams = models.IntegerField()
    no_of_players = models.IntegerField("No. of players per team", default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    start_date_time = models.DateTimeField(verbose_name="Start Date and Time")
    end_date_time = models.DateTimeField(verbose_name="End Date and Time")
    venue = models.CharField(max_length=128)
    
    def __str__(self):
        return self.name

tournament/views.py
from django.shortcuts import render
from django.views.generic import View, CreateView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin

from .models import *

from bootstrap_datepicker_plus import DateTimePickerInput
from matchs.models import Match
from teams.models import Team
from players.models import Player

class TournamentListView(LoginRequiredMixin, View):
    def get(self, request):
        tl = Tournament.objects.all().filter(user=self.request.user)

        ctx = {'tournament_list': tl}
        return render(request, 'tournament/tournament_list.html', ctx)

class TournamentCreateView(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = Tournament
    fields = ['name', 'no_of_overs', 'no_of_teams', 'no_of_players', 'start_date_time', 'end_date_time', 'venue',]
    success_url = reverse_lazy('tournaments:all')
    success_message = "Tournament Created!!"
    
    def get_form(self):
         form = super().get_form()
         form.fields['start_date_time'].widget = DateTimePickerInput()
         form.fields['end_date_time'].widget = DateTimePickerInput()
         return form
     
    def form_valid(self, form):
        print('form_valid called')
        object = form.save(commit=False)
        object.user = self.request.user
        object.save()
        return super(TournamentCreateView, self).form_valid(form)
    
class TournamentDetailView(DetailView):
    model = Tournament
    template_name = "tournament/tournament_view.html"
    
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['match_list'] = Match.objects.filter(tournament=kwargs.get('object'))
        context['teamscount'] = Team.objects.filter(tournament=kwargs.get('object')).count()
        context['playercount'] = Player.objects.filter(tournament=kwargs.get('object')).count()
        return context

tournament/templates/tournament/tournament_form.html
{% extends 'menu.html' %}
{% load crispy_forms_tags %}
{% block content %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{{ form.media }}
<form
  action="{% url 'tournaments:create' %}"
  method="post"
  id="upload_form"
  enctype="multipart/form-data"
>
  {% csrf_token %} {{ form|crispy }}
  <div class="form-group">
    <button class="btn btn-outline-info" type="submit">Create</button>
    <input class="btn btn-danger" type="submit" onclick="window.location='{% url 'tournaments:all' %}' ; return false;" value="Cancel" />
  </div>
</form>
{% endblock content %}

tournament/templates/tournament/tournament_list.html
{% extends 'menu.html' %}

{% block content %}
  <h1>Tournament List</h1>
  {% if tournament_list %}
  <ul class="list-group">
    {% for tournament in tournament_list %}
        {% if user.username == tournament.user.username %}
            <li class="list-group-item list-group-item-action" onclick="window.location.href='{% url 'tournaments:detail' tournament.id %}'">
                {{ tournament.name }} ({{ tournament.venue }})
                {% comment %} (<a href="{% url 'autoupdate' tournament.id %}">Update</a> |
                <a href="{% url 'autodelete' auto.id %}">Delete</a>) <br/>
                {{ auto.comments }} ({{ auto.mileage }} miles) {% endcomment %}
            </li>
        {% endif %}
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no tournaments available.</p>
  {% endif %}
  {% comment %} <p>
  <a href="{% url 'makeall' %}">View makes</a> ({{ make_count }}) |
    <a href="{% url 'makecreate' %}">Add a make</a>
  </p> {% endcomment %}
{% endblock %}

tournament/templates/tournament/tournament_view.html
{% extends 'menu.html' %}

{% block content %}
    <div class="row">
        <div class="col-8">
            <table class="table table-bordered table-hover">
            <tr>
                <th scope="col">Match between</th>
                <th scope="col">Winner</th>
            </tr>
            {% for match in match_list %}
                <tr>
                    <td>
                        {{ match.team1.name }} vs {{ match.team2.name }}
                    </td>
                    <td>
                        {% if match.winner and match.winner == match.team1 or match.winner == match.team1 %}
                            {{ match.winner.name }}
                        {% else %}
                            TBD
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </table>
        </div>
        <div class="col-4">
            {% if teamscount < tournament.no_of_teams %}
                <button class="btn btn-primary" onclick="window.location.href='{% url 'teams:addteam' tournament.id %}'">Add Team ({{ teamscount }}/{{ tournament.no_of_teams }})</button>
            {% endif %}
                <button class="btn btn-primary" style="float: right;" onclick="window.location.href='{% url 'match:addmatch' tournament.id %}'">Add Match</button>
            {% if playercount < tournament.no_of_players %}
                <button class="btn btn-primary" onclick="window.location.href='{% url 'players:addplayer' tournament.id %}'">Add Player ({{ playercount }}/{{ tournament.no_of_players }})</button>
            {% endif %}
        </div>
    </div>

{% endblock content %}